customize help
Yamato-Security/takajo pull request #18
Opened 2022-10-08 03:04 UTC by YamatoSecurity

closes #17

2022-10-08 03:06 UTC, YamatoSecurity commented
Rust 4 subcommandのヘルプメニューに近いメニューにしてみました。
<img width="1129" alt="Screen Shot 2022-10-08 at 12 05 20" src="https://user-images.githubusercontent.com/71482215/194685063-f2e2c35f-b577-402c-abaf-6c6f839bb1d9.png">

2022-10-08 03:24 UTC, hitenkoku requested changes
コメントを2件入れましたのでご確認のほどよろしくお願いいたします。

2022-10-08 03:24 UTC, hitenkoku commented on src/takajo.nim
> +      doc = "List up unused rules. (Ex: \"takajo.exe unused-rules -t ../hayabusa/timeline.csv -r ../hayabusa/rules\")",
個々のex の部分が実行したときにかなり見づらいのでUsageの中に書けるのであればそちらの方で書いてしまったほうが良いと思います。 helpオプションをつけた時にもかなり長くなっており、読みづらいです。

2022-10-08 03:24 UTC, hitenkoku commented on src/takajo.nim
> +      doc = "List up undetected evtx files. (Ex: \"takajo.exe undetected-evtx -t ../hayabusa/timeline.csv -e ../hayabusa-sample-evtx\")",
個々のex の部分が実行したときにかなり見づらいのでUsageの中に書けるのであればそちらの方で書いてしまったほうが良いと思います。 helpオプションをつけた時にもかなり長くなっており、読みづらいです。

2022-10-08 20:42 UTC, YamatoSecurity commented
そうですね。そこに書きたくなかったのですが、`./takajo undetected-evtx -h`のヘルプメニューをカスタマイズする方法が分からなかったので、`./takajo undetected-evtx -h`の時だけ表示できませんでした。サブコマンドのヘルプメニューをカスタマイズする方法分かりますか？

2022-10-08 22:14 UTC, YamatoSecurity commented
取り敢えずこんな感じでExamplesを移動しました：
<img width="593" alt="Screen Shot 2022-10-09 at 7 13 15" src="https://user-images.githubusercontent.com/71482215/194729612-ed5ae420-39e0-4f28-9e4f-5562d8f50497.png">

どうですか？

2022-10-09 02:19 UTC, hitenkoku commented
はい。ずっと見やすくなったと思います。問題ないと思います。

2022-10-09 02:20 UTC, hitenkoku commented on src/takajo.nim
> +      doc = "List up undetected evtx files. (Ex: \"takajo.exe undetected-evtx -t ../hayabusa/timeline.csv -e ../hayabusa-sample-evtx\")",
https://github.com/Yamato-Security/takajo/pull/18/commits/97ad45f0b9fc2c31d154f3e5c4f7195817fb8e22 で解決しました

2022-10-09 02:20 UTC, hitenkoku commented on src/takajo.nim
> +      doc = "List up unused rules. (Ex: \"takajo.exe unused-rules -t ../hayabusa/timeline.csv -r ../hayabusa/rules\")",
https://github.com/Yamato-Security/takajo/commit/97ad45f0b9fc2c31d154f3e5c4f7195817fb8e22 で解決しました

2022-10-09 02:20 UTC, hitenkoku approved these changes
御対応ありがとうございます。問題ないと思います。

2022-10-09 02:21 UTC, merged